context("checks RodentAbundance.R output")

download_observations('.')

test_that("data generated by default setting is same", {
  data = abundance(".", level='Site',
                   type="Rodents", length="all", unknowns=F, incomplete=F,
                   shape="crosstab", time="period")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "77de6c10e2a32f6e4bb1c3117cbe20ea")
})

test_that("data generated by level=treatment, length=long-term is same", {
  data = abundance(".", level='treatment', length="long-term")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "a271b23c61defaa4f3e7633f59c9b95c")
})

test_that("data generated by level=plot, time=newmoon, type=granivore, shape=flat
          is same", {
  data = abundance(".", level='plot', type="granivores",
                   shape="flat", time="newmoon")
  data = data %>% dplyr::filter(newmoonnumber < 465)
  expect_identical(digest::digest(data), "321ef477800844f0fe0e92074a600246")
})

test_that("data generated by unknowns=T, incomplete=T is same", {
            data = abundance(".", incomplete=T, unknowns = T)
            data = data %>% dplyr::filter(period < 434)
            expect_identical(digest::digest(data), "d3e9c6b953d2187964f42f012436924b")
          })

