context("Regression tests for rodent, ant and plant output")

portal_data_path <- tempdir()
download_observations(portal_data_path)

test_that("biomass data calculations for level = plot are the same", {
  data_tables <- load_data(portal_data_path, download_if_missing = TRUE,
                           clean = TRUE)
  expect_identical(digest::digest(data_tables), "0be3ea249b94c5128a606595bb7876b8")

  level <- "plot"
  type <- "rodents"
  shape <- "crosstab"
  time <- "period"
  output <- "biomass"
  fillweight <- TRUE
  unknowns <- FALSE
  min_traps <- 1
  min_plots <- 24
  effort <- FALSE
  na_drop <- FALSE
  zero_drop <- FALSE

  trapping_data_partial <- portalr:::filter_plots(data_tables$trapping_table, "all")
  expect_identical(digest::digest(trapping_data_partial), "89f9ca07740adc85caaa03c03d221f93") # fails

  trapping_data <- portalr:::join_plots_to_trapping(trapping_data_partial, data_tables$plots_table)
  expect_identical(digest::digest(trapping_data), "a820595782af6b3613d03944d0a91fb9") # passes

  out_1 <- clean_rodent_data(data_tables, fillweight, type, unknowns)
  expect_identical(digest::digest(out_1), "6b357833055aa8234589c0407ccfbff7") # passes

  grouping <- rlang::quos(period, plot, species)
  wt <- rlang::quo(wgt)

  out_2a <- dplyr::count(out_1, period, plot, species, wt = wgt)
  expect_identical(digest::digest(out_2a), "c1cfe5da946e8386234f9cee3a59d42a") # passes

  out_2b <- tidyr::complete(out_2a, period, plot, species, fill = list(n = as.integer(0)))
  expect_identical(digest::digest(out_2b), "a107bf45e1897ea3be52fe946e220b6a") # passes

  out_2c <- dplyr::right_join(out_2b, trapping_data, by = c("period", "plot"))
  expect_identical(digest::digest(out_2c), "273c1865086174efaceea0a7b1372a61") # passes

  out_2d <- dplyr::select(out_2c, period, plot, species, n, effort, treatment)
  expect_identical(digest::digest(out_2d), "924f3e69e155d8f19da85d77ddecab2f") # passes

  out_2e <- dplyr::filter(out_2d, !is.na(species))
  expect_identical(digest::digest(out_2e), "924f3e69e155d8f19da85d77ddecab2f") # passes

  out_2f <- dplyr::mutate(out_2e,
                          n = replace(n, effort < min_traps, NA),
                          effort = replace(effort, effort < min_traps, NA))
  expect_identical(digest::digest(out_2f), "4d67ce0dee4fc8f127cce17d2c58f6b0") # fails

  out_2 <- dplyr::rename(out_2f, biomass := n)
  expect_identical(digest::digest(out_2), "09cfce087a9d75c680496e4a062e66ba") # fails

  # out_2 <- portalr:::make_plot_data(out_1, trapping_data, output, min_traps)
  # expect_identical(digest::digest(out_2), "09cfce087a9d75c680496e4a062e66ba") #fails

  out_3 <- portalr:::make_level_data(out_2, data_tables$trapping_table, level,
                                     output, min_plots, min_traps)
  expect_identical(digest::digest(out_3), "d2e06beb7ebfa3e6e32524bc9d10dd23") # fails

  out <- portalr:::prep_rodent_output(out_3, data_tables, time, effort, na_drop,
                                      zero_drop, shape, level, output)
  expect_identical(digest::digest(out), "9781fbfa166ce2f9454bdea8d1478b7f") # fails

  data <- dplyr::filter(out, period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "aa996a24cf58b1315a3a1dc29349de23") # fails
})

test_that("biomass data generated by level = plot is same", {
  data <- biomass(portal_data_path, level = "plot")
  data <- dplyr::filter(data, period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "aa996a24cf58b1315a3a1dc29349de23")
})

test_that("data generated by default setting is same (shrub_cover)", {
  data <- shrub_cover(path = portal_data_path, type = "Shrubs",
                      plots = "all", unknowns = FALSE,
                      correct_sp = TRUE)
  data <- dplyr::filter(data, year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "a6003563a3817bf6d187565e0ef7d0ac")
})

test_that("data generated by default setting is same (ant colony_presence_absence)", {
  data <- colony_presence_absence(portal_data_path, level = 'Site', rare_sp = F, unknowns = F)
  data <- dplyr::filter(data, year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "cde8c5498581739d29406c107ff09de6")
})

test_that("data generated by default setting is same (weather)", {
  data <- weather(path = portal_data_path)
  data <- data %>% dplyr::filter(year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "86f58f054c6d7ee5370cb1ad022f3fe6")
})

test_that("weather calculations for fill = TRUE are the same", {
  level <- "daily"
  path <- portal_data_path
  fill <- TRUE
  level <- tolower(level)

  weather_new <- read.csv(portalr:::full_path('PortalData/Weather/Portal_weather.csv', path),
                          na.strings = c(""), stringsAsFactors = FALSE)
  expect_identical(digest::digest(weather_new), "b09dc1fb06e38e0e4fa131ad6ec832ff") # fails

  weather_old <- read.csv(portalr:::full_path('PortalData/Weather/Portal_weather_19801989.csv', path),
                          na.strings = c("-99"), stringsAsFactors = FALSE)
  expect_identical(digest::digest(weather_old), "ba93db83a42609ba7cde8725513585ff") # fails

  moon_dates <- read.csv(portalr:::full_path('PortalData/Rodents/moon_dates.csv', path),
                         na.strings = c(""), stringsAsFactors = FALSE)
  expect_identical(digest::digest(moon_dates), "01ccc37cd386a5df0e36315cd6ec44a6") # passes

  ###########Summarise by Day ----------------------
  days <- weather_new %>%
    dplyr::group_by(year, month, day) %>%
    dplyr::summarize(mintemp = min(airtemp), maxtemp = max(airtemp), meantemp = mean(airtemp), precipitation = sum(precipitation), battv = min(battv, na.rm = TRUE))
  expect_identical(digest::digest(days), "b6fc5b2257de402e4d3e53003511dd92") # passes

  weather <- dplyr::bind_rows(weather_old[1:3442, ], days)  %>%
    dplyr::mutate(locally_measured = TRUE, battv = ifelse(is.infinite(battv), NA, battv), battery_low = ifelse(battv<11, TRUE, FALSE)) %>%
    dplyr::select(year, month, day, mintemp, maxtemp, meantemp, precipitation, locally_measured, battery_low)
  expect_identical(digest::digest(weather), "e62f25d89db5b5ca93705704acff780a") # fails

  weather <- portalr:::fill_missing_weather(weather, path)
  expect_identical(digest::digest(weather), "43bb74887f62ca34ec414bba1b3075a6")# fails

  data <- weather %>% dplyr::filter(year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "6b4c82fd96876732b585a45228463a62") # fails
})

test_that("data generated by fill = TRUE is same (weather)", {
  data <- weather(fill = TRUE, path = portal_data_path)
  data <- data %>% dplyr::filter(year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "6b4c82fd96876732b585a45228463a62") # fails
})
