context("checks RodentData.R output")

test_that("data generated by default setting is same", {
          data = abundance(".", level='Site',
                           type="Rodents", length="all", unknowns=F, incomplete=F,
                           shape="crosstab", time="period")
          data = data %>% dplyr::filter(period < 434)
          attributes(data) <- attributes(data)[sort(names(attributes(data)))]
          expect_identical(digest::digest(data), "a373e851bc3d417aba6ac00356dbe4bf")
})

test_that("data generated by level=treatment, length=long-term is same", {
          data = abundance(".", level='treatment', length="long-term")
          data = data %>% dplyr::filter(period < 434)
          attributes(data) <- attributes(data)[sort(names(attributes(data)))]
          expect_identical(digest::digest(data), "0b209182a33b625586c342c323e7d9ae")
})

test_that("data generated by level=plot, time=newmoon, type=granivore, shape=flat
          is same", {
          data = abundance(".", level='plot', type="granivores",
                           shape="flat", time="newmoon")
          data = data %>% dplyr::filter(newmoonnumber < 465)
          attributes(data) <- attributes(data)[sort(names(attributes(data)))]
          expect_identical(digest::digest(data), "44912aa12553a480477595fe50e0a4fa")
})

test_that("data generated by unknowns=T, incomplete=T is same", {
            data = abundance(".", incomplete=T, unknowns = T)
            data = data %>% dplyr::filter(period < 434)
            attributes(data) <- attributes(data)[sort(names(attributes(data)))]
            expect_identical(digest::digest(data), "716cba45b04466dea49bccd2844ef5da")
          })

test_that("biomass data generated by level=plot is same", {
          data = biomass(".", level="plot")
          data = data %>% dplyr::filter(period < 434)
          attributes(data) <- attributes(data)[sort(names(attributes(data)))]
          expect_identical(digest::digest(data), "822f2c1a2b87218317ae414756cd5eb8")
})

test_that("biomass data generated by incomplete=T is same", {
          data = biomass(".", incomplete=T)
          data = data %>% dplyr::filter(period < 434)
          attributes(data) <- attributes(data)[sort(names(attributes(data)))]
          expect_identical(digest::digest(data), "78312c1d686891d5b7b4e2f116878221")
})

