context("checks RodentData.R output")

test_that("data generated by default setting is same", {
  data = abundance(".", level='Site',
                   type="Rodents", length="all", unknowns=F, incomplete=F,
                   shape="crosstab", time="period")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "cdd1c1ee86fd7bce6344f69cf2ce360f")
})

test_that("data generated by level=treatment, length=long-term is same", {
  data = abundance(".", level='treatment', length="long-term")
  data = data %>% dplyr::filter(period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "0a36f4c29c35df9a70087713e9d5f6a5")
})

test_that("data generated by level=plot, time=newmoon, type=granivore, shape=flat
          is same", {
  data = abundance(".", level='plot', type="granivores",
                   shape="flat", time="newmoon")
  data = data %>% dplyr::filter(newmoonnumber < 465)
  expect_identical(digest::digest(data), "24e4eca33ae7793fa91f1257a6920c02")
})

test_that("data generated by unknowns=T, incomplete=T is same", {
            data = abundance(".", incomplete=T, unknowns = T)
            data = data %>% dplyr::filter(period < 434)
            expect_identical(digest::digest(data), "7aa41eb12bb0eafb8916b6d9b1458612")
          })

test_that("biomass data generated by level=plot is same", {
  data = biomass(".", level="plot")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "928d7625c479af94f239b2e8447c356a")
})

test_that("biomass data generated by incomplete=T is same", {
  data = biomass(".", incomplete=T)
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "d2fb04be3bf47357ecdcd60597455c6e")
})

