context("Regression tests for rodent and plant output")

test_that("data generated by default setting is same", {
  data <- abundance(".", level = 'Site',
                    type = "Rodents", length = "all", unknowns = F, min_plots = 24,
                    shape = "crosstab", time = "period")
  data <- data %>% dplyr::filter(period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "f7365a1b64bd3aa30579abd37c6de863")
})

test_that("data generated by level = treatment, length = longterm is same", {
  data <- abundance(".", level = 'treatment', length = "longterm")
  data <- data %>% dplyr::filter(period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "fb74b465a0e8ced4fbad4567bf6bf03b")
})

test_that("data generated by level = plot, time = newmoon, type = granivore, shape = flat
     is same", {
       data <- abundance(".", level = 'plot', type = "granivores",
                         shape = "flat", time = "newmoon")
       data <- data %>% dplyr::filter(newmoonnumber < 465)
       attributes(data) <- attributes(data)[sort(names(attributes(data)))]
       expect_identical(digest::digest(data), "e7f1f4a8bda79171e134cf1d87d2514a")
     })

test_that("data generated by unknowns = T, min_plots = 1 is same", {
  data <- abundance(".", min_plots = 1, unknowns = TRUE)
  data <- data %>% dplyr::filter(period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "716cba45b04466dea49bccd2844ef5da")
})

test_that("data generated by plots = c(4, 8, 10, 12) is same", {
  data <- get_rodent_data(path = ".", plots = c(4, 8, 10, 12),
                  na_drop = TRUE, zero_drop = FALSE)
  data <- data %>% dplyr::filter(period < 450)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "c4eb4083894c3790ceeba6b8ef8d3579")
})

test_that("biomass data generated by level = plot is same", {
  data <- biomass(".", level = "plot")
  data <- data %>% dplyr::filter(period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "68a690aa740bcea170af471b1e6d8754")
})

test_that("biomass data generated by min_plots = 1 is same", {
  data <- biomass(".", min_plots = 1)
  data <- data %>% dplyr::filter(period < 434)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "78312c1d686891d5b7b4e2f116878221")
})

test_that("data generated by default setting is same (plants)", {
  data <- plant_abundance(".", level = 'Site',
                          type = "All", length = "all", unknowns = FALSE,
                          correct_sp = TRUE, shape = "flat")
  data <- data %>% dplyr::filter(year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "a81e273214c0eaddadd42755e5b2887a")
})

test_that("data generated by type = Shrubs, unknowns = T, correct_sp = F is same (plants)", {
  data <- plant_abundance(".", level = 'Site',
                          type = "Shrubs", length = "all", unknowns = TRUE,
                          correct_sp = FALSE, shape = "flat")
  data <- data %>% dplyr::filter(year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "8213afa103bd1ac96e04cf5e2b1f941d")
})

test_that("data generated by level = Plot, type = Annuals, length = longterm is same (plants)", {
  data <- plant_abundance(".", level = 'Plot',
                          type = "Annuals", length = "longterm")
  data <- data %>% dplyr::filter(year < 2015)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_identical(digest::digest(data), "10a08dc4bd6d63c31270acc7f678134d")
})
