context("checks RodentData.R output")

test_that("data generated by default setting is same", {
  data = abundance(".", level='Site',
                   type="Rodents", length="all", unknowns=F, incomplete=F,
                   shape="crosstab", time="period")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "1c8424010f7ce20670c9cc5ade5345d0")
})

test_that("data generated by level=treatment, length=long-term is same", {
  data = abundance(".", level='treatment', length="long-term")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "25bedd8d16d1951677ecad26eb994a64")
})

test_that("data generated by level=plot, time=newmoon, type=granivore, shape=flat
          is same", {
  data = abundance(".", level='plot', type="granivores",
                   shape="flat", time="newmoon")
  data = data %>% dplyr::filter(newmoonnumber < 465)
  expect_identical(digest::digest(data), "113b996f85266b76bf4734537a797b23")
})

test_that("data generated by unknowns=T, incomplete=T is same", {
            data = abundance(".", incomplete=T, unknowns = T)
            data = data %>% dplyr::filter(period < 434)
            expect_identical(digest::digest(data), "b1c1bd63dc2d2d8708e6d572686038d5")
          })

test_that("biomass data generated by level=plot is same", {
  data = biomass(".", level="plot")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "db303dbd95b94d0cb5ca45204499ecff")
})

test_that("biomass data generated by incomplete=T is same", {
  data = biomass(".", incomplete=T)
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "78c0bb290a76cb6b3b4ed21dae1750fe")
})

