context("checks RodentAbundance.R output")

download_observations('.')

test_that("data generated by default setting is same", {
  data = abundance(".", level='Site',
                   type="Rodents", length="all", unknowns=F, incomplete=F,
                   shape="crosstab", time="period")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "cdd1c1ee86fd7bce6344f69cf2ce360f")
})

test_that("data generated by level=treatment, length=long-term is same", {
  data = abundance(".", level='treatment', length="long-term")
  data = data %>% dplyr::filter(period < 434)
  expect_identical(digest::digest(data), "e7c53159928f9f58b6ee17a631db3c4c")
})

test_that("data generated by level=plot, time=newmoon, type=granivore, shape=flat
          is same", {
  data = abundance(".", level='plot', type="granivores",
                   shape="flat", time="newmoon")
  data = data %>% dplyr::filter(newmoonnumber < 465)
  expect_identical(digest::digest(data), "be43b340ba0d23d260a6798b85ab738b")
})

test_that("data generated by unknowns=T, incomplete=T is same", {
            data = abundance(".", incomplete=T, unknowns = T)
            data = data %>% dplyr::filter(period < 434)
            expect_identical(digest::digest(data), "ea6f9644cd0e8c7c25eb76044d377511")
          })

